
import { Deck } from './types';

export const N4_KANJI_DATA = [
  { id: 1, kanji: "私", meaning: "ကျွန်ုပ် (I/Me)", onyomi: "シ", kunyomi: "わたし", examples: [{ word: "私", reading: "watashi", mean: "ကျွန်ုပ်" }, { word: "私立", reading: "shiritsu", mean: "ပုဂ္ဂလိက" }] },
  { id: 2, kanji: "親", meaning: "မိဘ (Parent)", onyomi: "シン", kunyomi: "おや", examples: [{ word: "両親", reading: "ryoushin", mean: "မိဘနှစ်ပါး" }, { word: "親切", reading: "shinsetsu", mean: "ကြင်နာသော" }] },
  { id: 3, kanji: "切", meaning: "ဖြတ်သည် (Cut)", onyomi: "セツ", kunyomi: "きる", examples: [{ word: "大切", reading: "taisetsu", mean: "အရေးကြီးသော" }, { word: "切手", reading: "kitte", mean: "တံဆိပ်ခေါင်း" }] },
  { id: 4, kanji: "手", meaning: "လက် (Hand)", onyomi: "シュ", kunyomi: "て", examples: [{ word: "歌手", reading: "kashu", mean: "အဆိုတော်" }, { word: "上手", reading: "jouzu", mean: "ကျွမ်းကျင်သော" }] },
  { id: 5, kanji: "家", meaning: "အိမ် (House)", onyomi: "カ/ケ", kunyomi: "いえ/や", examples: [{ word: "家族", reading: "kazoku", mean: "မိသားစု" }, { word: "家主", reading: "yanushi", mean: "အိမ်ရှင်" }] },
  { id: 6, kanji: "族", meaning: "မျိုးနွယ် (Tribe/Family)", onyomi: "ゾク", kunyomi: "-", examples: [{ word: "家族", reading: "kazoku", mean: "မိသားစု" }, { word: "親族", reading: "shinzoku", mean: "ဆွေမျိုး" }] },
  { id: 7, kanji: "母", meaning: "အမေ (Mother)", onyomi: "ボ", kunyomi: "はは", examples: [{ word: "お母さん", reading: "okaasan", mean: "အမေ" }, { word: "母校", reading: "bokou", mean: "ကျောင်းတော်" }] },
  { id: 8, kanji: "父", meaning: "အဖေ (Father)", onyomi: "フ", kunyomi: "ちち", examples: [{ word: "お父さん", reading: "otousan", mean: "အဖေ" }, { word: "父母", reading: "fubo", mean: "မိဘ" }] },
  { id: 9, kanji: "兄", meaning: "အစ်ကို (Older Brother)", onyomi: "キョウ", kunyomi: "あに", examples: [{ word: "お兄さん", reading: "oniisan", mean: "အစ်ကို" }, { word: "兄弟", reading: "kyoudai", mean: "ညီအစ်ကို" }] },
  { id: 10, kanji: "姉", meaning: "အစ်မ (Older Sister)", onyomi: "シ", kunyomi: "あね", examples: [{ word: "お姉さん", reading: "oneesan", mean: "အစ်မ" }, { word: "姉妹", reading: "shimai", mean: "ညီအစ်မ" }] },
  { id: 11, kanji: "弟", meaning: "ညီ/မောင် (Younger Brother)", onyomi: "ダイ", kunyomi: "おとうと", examples: [{ word: "弟子", reading: "deshi", mean: "တပည့်" }, { word: "義弟", reading: "gitei", mean: "ယောက္ခထီး" }] },
  { id: 12, kanji: "妹", meaning: "ညီမ/နှမ (Younger Sister)", onyomi: "マイ", kunyomi: "いもうと", examples: [{ word: "姉妹", reading: "shimai", mean: "ညီအစ်မ" }] },
  { id: 13, kanji: "勉", meaning: "ကြိုးစားသည် (Exertion)", onyomi: "ベン", kunyomi: "つと.める", examples: [{ word: "勉強", reading: "benkyou", mean: "စာသင်သည်" }] },
  { id: 14, kanji: "強", meaning: "သန်မာသော (Strong)", onyomi: "キョウ", kunyomi: "つよ.い", examples: [{ word: "勉強", reading: "benkyou", mean: "စာသင်သည်" }, { word: "強力", reading: "kyouryoku", mean: "အားကောင်းသော" }] },
  { id: 15, kanji: "道", meaning: "လမ်း (Road/Way)", onyomi: "ドウ", kunyomi: "みち", examples: [{ word: "道路", reading: "douro", mean: "လမ်းမကြီး" }, { word: "茶道", reading: "sadou", mean: "လက်ဖက်ရည်ဖျော်နည်း" }] },
  { id: 16, kanji: "目", meaning: "မျက်စိ (Eye)", onyomi: "モク", kunyomi: "め", examples: [{ word: "目的", reading: "mokuteki", mean: "ရည်ရွယ်ချက်" }, { word: "目次", reading: "mokuji", mean: "မာတိကာ" }] },
  { id: 17, kanji: "耳", meaning: "နား (Ear)", onyomi: "ジ", kunyomi: "みみ", examples: [{ word: "耳鼻科", reading: "jibika", mean: "နားနှာခေါင်းလည်ချောင်းဌာန" }] },
  { id: 18, kanji: "口", meaning: "ပါးစပ် (Mouth)", onyomi: "コウ", kunyomi: "くち", examples: [{ word: "人口", reading: "jinkou", mean: "လူဦးရေ" }, { word: "入口", reading: "iriguchi", mean: "အပေါက်" }] },
  { id: 19, kanji: "足", meaning: "ခြေထောက် (Foot/Leg)", onyomi: "ソク", kunyomi: "あし", examples: [{ word: "遠足", reading: "ensoku", mean: "အပန်းဖြေခရီး" }, { word: "足りる", reading: "tariru", mean: "လုံလောက်သည်" }] },
  { id: 20, kanji: "立", meaning: "ရပ်သည် (Stand)", onyomi: "リツ", kunyomi: "た.つ", examples: [{ word: "国立", reading: "kokuritsu", mean: "နိုင်ငံတော်ပိုင်" }, { word: "建立", reading: "kenryu", mean: "တည်ဆောက်သည်" }] },
  // Adding more N4 standard Kanji (Condensed for performance but covering core items)
  { id: 21, kanji: "体", meaning: "ခန္ဓာကိုယ် (Body)", onyomi: "タイ", kunyomi: "からだ", examples: [{ word: "体力", reading: "tairyoku", mean: "ကိုယ်ကာယခွန်အား" }] },
  { id: 22, kanji: "頭", meaning: "ခေါင်း (Head)", onyomi: "トウ", kunyomi: "あたま", examples: [{ word: "頭痛", reading: "zutsuu", mean: "ခေါင်းကိုက်ခြင်း" }] },
  { id: 23, kanji: "顔", meaning: "မျက်နှာ (Face)", onyomi: "ガン", kunyomi: "かお", examples: [{ word: "洗顔", reading: "sengan", mean: "မျက်နှာသစ်ခြင်း" }] },
  { id: 24, kanji: "声", meaning: "အသံ (Voice)", onyomi: "セイ", kunyomi: "こえ", examples: [{ word: "声明", reading: "seimei", mean: "ထုတ်ပြန်ချက်" }] },
  { id: 25, kanji: "心", meaning: "နှလုံးသား (Heart/Mind)", onyomi: "シン", kunyomi: "こころ", examples: [{ word: "心配", reading: "shinpai", mean: "စိတ်ပူသည်" }] },
  { id: 26, kanji: "思", meaning: "ထင်သည်/တွေးသည် (Think)", onyomi: "シ", kunyomi: "おも.う", examples: [{ word: "思い出", reading: "omoide", mean: "အမှတ်တရ" }] },
  { id: 27, kanji: "知", meaning: "သိသည် (Know)", onyomi: "チ", kunyomi: "し.る", examples: [{ word: "知識", reading: "chishiki", mean: "ဗဟုသုတ" }] },
  { id: 28, kanji: "答", meaning: "အဖြေ (Answer)", onyomi: "トウ", kunyomi: "こた.える", examples: [{ word: "回答", reading: "kaitou", mean: "အဖြေလွှာ" }] },
  { id: 29, kanji: "考", meaning: "စဉ်းစားသည် (Consider)", onyomi: "コウ", kunyomi: "かんが.える", examples: [{ word: "思考", reading: "shikou", mean: "အတွေးအခေါ်" }] },
  { id: 30, kanji: "楽", meaning: "ပျော်ရွှင်သော/လွယ်ကူသော (Enjoy)", onyomi: "ガク/ラク", kunyomi: "たの.しい", examples: [{ word: "音楽", reading: "ongaku", mean: "ဂီတ" }, { word: "楽", reading: "raku", mean: "သက်တောင့်သက်သာ" }] },
  { id: 31, kanji: "歌", meaning: "သီချင်း (Song)", onyomi: "カ", kunyomi: "うた", examples: [{ word: "歌手", reading: "kashu", mean: "အဆိုတော်" }] },
  { id: 32, kanji: "音", meaning: "အသံ (Sound)", onyomi: "オン", kunyomi: "おと", examples: [{ word: "発音", reading: "hatsuon", mean: "အသံထွက်" }] },
  { id: 33, kanji: "学", meaning: "ပညာသင်သည် (Study)", onyomi: "ガク", kunyomi: "まな.ぶ", examples: [{ word: "学生", reading: "gakusei", mean: "ကျောင်းသား" }] },
  { id: 34, kanji: "校", meaning: "ကျောင်း (School)", onyomi: "コウ", kunyomi: "-", examples: [{ word: "小学校", reading: "shougakkou", mean: "မူလတန်းကျောင်း" }] },
  { id: 35, kanji: "教", meaning: "သင်ကြားသည် (Teach)", onyomi: "キョウ", kunyomi: "おし.える", examples: [{ word: "教室", reading: "kyoushitsu", mean: "စာသင်ခန်း" }] },
  { id: 36, kanji: "室", meaning: "အခန်း (Room)", onyomi: "シツ", kunyomi: "-", examples: [{ word: "茶室", reading: "chashitsu", mean: "လက်ဖက်ရည်ခန်း" }] },
  { id: 37, kanji: "習", meaning: "သင်ယူသည် (Learn)", onyomi: "シュウ", kunyomi: "なら.う", examples: [{ word: "予習", reading: "yoshuu", mean: "ကြိုတင်လေ့ကျင့်ခြင်း" }] },
  { id: 38, kanji: "英", meaning: "အင်္ဂလိပ် (English)", onyomi: "エイ", kunyomi: "-", examples: [{ word: "英語", reading: "eigo", mean: "အင်္ဂလိပ်စာ" }] },
  { id: 39, kanji: "国", meaning: "နိုင်ငံ (Country)", onyomi: "コク", kunyomi: "くに", examples: [{ word: "韓国", reading: "kankoku", mean: "ကိုးရီးယား" }] },
  { id: 40, kanji: "地", meaning: "မြေပြင် (Earth)", onyomi: "チ/ジ", kunyomi: "-", examples: [{ word: "地下鉄", reading: "chikatetsu", mean: "မြေအောက်ရထား" }] },
  { id: 41, kanji: "図", meaning: "ပုံ (Map/Drawing)", onyomi: "ズ/ト", kunyomi: "はか.る", examples: [{ word: "図書館", reading: "toshokan", mean: "စာကြည့်တိုက်" }] },
  { id: 42, kanji: "館", meaning: "အဆောက်အဦး (Building/Hall)", onyomi: "カン", kunyomi: "やか", examples: [{ word: "映画館", reading: "eigakan", mean: "ရုပ်ရှင်ရုံ" }] },
  { id: 43, kanji: "茶", meaning: "လက်ဖက်ရည် (Tea)", onyomi: "チャ/サ", kunyomi: "-", examples: [{ word: "お茶", reading: "ocha", mean: "လက်ဖက်ရည်" }, { word: "茶道", reading: "sadou", mean: "လက်ဖက်ရည်ဖျော်နည်း" }] },
  { id: 44, kanji: "酒", meaning: "အရက် (Sake/Alcohol)", onyomi: "シュ", kunyomi: "さけ/さか", examples: [{ word: "日本酒", reading: "nihonshu", mean: "ဂျပန်အရက်" }] },
  { id: 45, kanji: "写", meaning: "ကူးယူသည် (Copy/Photograph)", onyomi: "シャ", kunyomi: "うつ.す", examples: [{ word: "写真", reading: "shashin", mean: "ဓာတ်ပုံ" }] },
  { id: 46, kanji: "真", meaning: "အမှန် (Truth/Pure)", onyomi: "シン", kunyomi: "ま", examples: [{ word: "写真", reading: "shashin", mean: "ဓာတ်ပုံ" }, { word: "真ん中", reading: "mannaka", mean: "အလယ်ဗဟို" }] },
  { id: 47, kanji: "紙", meaning: "စက္ကူ (Paper)", onyomi: "シ", kunyomi: "かみ", examples: [{ word: "手紙", reading: "tegami", mean: "စာ" }] },
  { id: 48, kanji: "映", meaning: "ရောင်ပြန်ဟပ်သည် (Reflect/Project)", onyomi: "エイ", kunyomi: "うつ.る", examples: [{ word: "映画", reading: "eiga", mean: "ရုပ်ရှင်" }] },
  { id: 49, kanji: "画", meaning: "ရုပ်ပုံ (Movie/Picture)", onyomi: "ガ/カク", kunyomi: "-", examples: [{ word: "映画", reading: "eiga", mean: "ရုပ်ရှင်" }, { word: "計画", reading: "keikaku", mean: "အစီအစဉ်" }] },
  { id: 50, kanji: "店", meaning: "ဆိုင် (Shop)", onyomi: "テン", kunyomi: "みせ", examples: [{ word: "喫茶店", reading: "kissaten", mean: "ကော်ဖီဆိုင်" }, { word: "店員", reading: "tenin", mean: "ဆိုင်ဝန်ထမ်း" }] },
  { id: 51, kanji: "屋", meaning: "ဆိုင်/အိမ် (Store/House)", onyomi: "オク", kunyomi: "や", examples: [{ word: "本屋", reading: "hon-ya", mean: "စာအုပ်ဆိုင်" }, { word: "屋上", reading: "okujou", mean: "အမိုးထပ်" }] },
  { id: 52, kanji: "用", meaning: "အသုံးပြုသည် (Use/Business)", onyomi: "ヨウ", kunyomi: "もち.いる", examples: [{ word: "用事", reading: "youji", mean: "ကိစ္စ" }] },
  { id: 53, kanji: "送", meaning: "ပို့သည် (Send)", onyomi: "ソウ", kunyomi: "おく.る", examples: [{ word: "送信", reading: "soushin", mean: "ပေးပို့ခြင်း" }] },
  { id: 54, kanji: "転", meaning: "လှည့်သည် (Turn/Roll)", onyomi: "テン", kunyomi: "ころ.がる", examples: [{ word: "自転車", reading: "jitensha", mean: "စက်ဘီး" }, { word: "運転", reading: "unten", mean: "မောင်းနှင်ခြင်း" }] },
  { id: 55, kanji: "借", meaning: "ငှားသည် (Borrow)", onyomi: "シャク", kunyomi: "か.りる", examples: [{ word: "借金", reading: "shakkin", mean: "အကြွေး" }] },
  { id: 56, kanji: "貸", meaning: "ငှားရမ်းသည် (Lend)", onyomi: "タイ", kunyomi: "か.す", examples: [{ word: "貸出", reading: "kashidashi", mean: "ငှားရမ်းထုတ်ပေးခြင်း" }] },
  { id: 57, kanji: "終", meaning: "ပြီးဆုံးသည် (End)", onyomi: "シュウ", kunyomi: "お.わる", examples: [{ word: "終電", reading: "shuuden", mean: "နောက်ဆုံးရထား" }] },
  { id: 58, kanji: "始", meaning: "စတင်သည် (Begin)", onyomi: "シ", kunyomi: "はじ.める", examples: [{ word: "開始", reading: "kaishi", mean: "စတင်ခြင်း" }] },
  { id: 59, kanji: "昼", meaning: "နေ့လည် (Daytime/Noon)", onyomi: "チュウ", kunyomi: "ひる", examples: [{ word: "昼休み", reading: "hiruyasumi", mean: "နေ့လည်နားချိန်" }] },
  { id: 60, kanji: "夜", meaning: "ည (Night)", onyomi: "ヤ", kunyomi: "よる/よ", examples: [{ word: "今夜", reading: "konya", mean: "ယနေ့ည" }, { word: "夜中", reading: "yonaka", mean: "သန်းခေါင်" }] },
  { id: 61, kanji: "朝", meaning: "မနက် (Morning)", onyomi: "チョウ", kunyomi: "あさ", examples: [{ word: "朝食", reading: "choushoku", mean: "မနက်စာ" }] },
  { id: 62, kanji: "夕", meaning: "ညနေ (Evening)", onyomi: "セキ", kunyomi: "ゆう", examples: [{ word: "夕方", reading: "yuugata", mean: "ညနေခင်း" }] },
  { id: 63, kanji: "方", meaning: "ဘက်/လူ (Direction/Person)", onyomi: "ホウ", kunyomi: "かた", examples: [{ word: "方法", reading: "houhou", mean: "နည်းလမ်း" }, { word: "読み方", reading: "yomikata", mean: "ဖတ်နည်း" }] },
  { id: 64, kanji: "万", meaning: "တစ်သောင်း (Ten Thousand)", onyomi: "マン/バン", kunyomi: "-", examples: [{ word: "一万円", reading: "ichiman-en", mean: "တစ်သောင်းယန်း" }] },
  { id: 65, kanji: "円", meaning: "ယန်း/အဝိုင်း (Yen/Circle)", onyomi: "エン", kunyomi: "まる", examples: [{ word: "円い", reading: "marui", mean: "ဝိုင်းသော" }] },
  { id: 66, kanji: "百", meaning: "တစ်ရာ (Hundred)", onyomi: "ヒャク", kunyomi: "-", examples: [{ word: "三百", reading: "sanbyaku", mean: "သုံးရာ" }] },
  { id: 67, kanji: "千", meaning: "တစ်ထောင် (Thousand)", onyomi: "セン", kunyomi: "ち", examples: [{ word: "二千", reading: "nisen", mean: "နှစ်ထောင်" }] },
  { id: 68, kanji: "多", meaning: "များသော (Many)", onyomi: "タ", kunyomi: "おお.い", examples: [{ word: "多分", reading: "tabun", mean: "ဖြစ်နိုင်သည်" }] },
  { id: 69, kanji: "少", meaning: "နည်းသော (Few)", onyomi: "ショウ", kunyomi: "すく.ない/すこ.し", examples: [{ word: "少量", reading: "shouryou", mean: "ပမာဏအနည်းငယ်" }] },
  { id: 70, kanji: "古", meaning: "ဟောင်းသော (Old)", onyomi: "コ", kunyomi: "ふる.い", examples: [{ word: "中古", reading: "chuuko", mean: "တစ်ပတ်ရစ်" }] },
  { id: 71, kanji: "新", meaning: "သစ်သော (New)", onyomi: "シン", kunyomi: "あたら.しい", examples: [{ word: "新聞", reading: "shinbun", mean: "သတင်းစာ" }] },
  { id: 72, kanji: "安", meaning: "ဈေးပေါသော (Cheap/Quiet)", onyomi: "アン", kunyomi: "やす.い", examples: [{ word: "安心", reading: "anshin", mean: "စိတ်အေးရခြင်း" }] },
  { id: 73, kanji: "高", meaning: "မြင့်သော/ဈေးကြီးသော (High/Expensive)", onyomi: "コウ", kunyomi: "たか.い", examples: [{ word: "高校", reading: "koukou", mean: "အထက်တန်းကျောင်း" }] },
  { id: 74, kanji: "長", meaning: "ရှည်သော (Long)", onyomi: "チョウ", kunyomi: "なが.い", examples: [{ word: "社長", reading: "shachou", mean: "ကုမ္ပဏီဥက္ကဋ္ဌ" }] },
  { id: 75, kanji: "短", meaning: "တိုသော (Short)", onyomi: "タン", kunyomi: "みじか.い", examples: [{ word: "短時間", reading: "tanjikan", mean: "အချိန်တိုအတွင်း" }] },
  { id: 76, kanji: "明", meaning: "လင်းသော (Bright)", onyomi: "メイ/ミョウ", kunyomi: "あか.るい", examples: [{ word: "明日", reading: "ashita", mean: "မနက်ဖြန်" }] },
  { id: 77, kanji: "暗", meaning: "မှောင်သော (Dark)", onyomi: "アン", kunyomi: "くら.い", examples: [{ word: "暗号", reading: "angou", mean: "လျှို့ဝှက်ကုဒ်" }] },
  { id: 78, kanji: "広", meaning: "ကျယ်သော (Wide)", onyomi: "コウ", kunyomi: "ひろ.い", examples: [{ word: "広告", reading: "koukoku", mean: "ကြော်ငြာ" }] },
  { id: 79, kanji: "速", meaning: "မြန်သော (Fast)", onyomi: "ソク", kunyomi: "はや.い", examples: [{ word: "速度", reading: "sokudo", mean: "အမြန်နှုန်း" }] },
  { id: 80, kanji: "遅", meaning: "နှေးသော (Slow)", onyomi: "チ", kunyomi: "おそ.い", examples: [{ word: "遅刻", reading: "chikoku", mean: "နောက်ကျခြင်း" }] },
  { id: 81, kanji: "重", meaning: "လေးသော (Heavy)", onyomi: "ジュウ/チョウ", kunyomi: "おも.い", examples: [{ word: "重要", reading: "juuyou", mean: "အရေးကြီးသော" }] },
  { id: 82, kanji: "軽", meaning: "ပေါ့သော (Light)", onyomi: "ケイ", kunyomi: "かる.い", examples: [{ word: "軽食", reading: "keishoku", mean: "အပေါ့စားစားသောက်ဖွယ်" }] },
  { id: 83, kanji: "遠", meaning: "ဝေးသော (Far)", onyomi: "エン", kunyomi: "とお.い", examples: [{ word: "遠慮", reading: "enryo", mean: "အားနာခြင်း" }] },
  { id: 84, kanji: "近", meaning: "နီးသော (Near)", onyomi: "キン", kunyomi: "ちか.い", examples: [{ word: "最近", reading: "saikin", mean: "လတ်တလော" }] },
  { id: 85, kanji: "正", meaning: "မှန်ကန်သော (Correct)", onyomi: "セイ/ショウ", kunyomi: "ただ.しい", examples: [{ word: "正解", reading: "seikai", mean: "အဖြေမှန်" }] },
  { id: 86, kanji: "不", meaning: "မ... (Non/Un-)", onyomi: "フ/ブ", kunyomi: "-", examples: [{ word: "不便", reading: "fuben", mean: "အဆင်မပြေသော" }] },
  { id: 87, kanji: "同", meaning: "တူညီသော (Same)", onyomi: "ドウ", kunyomi: "おな.じ", examples: [{ word: "同時", reading: "douji", mean: "တစ်ချိန်တည်းမှာ" }] },
  { id: 88, kanji: "計", meaning: "တိုင်းတာသည် (Measure/Plan)", onyomi: "ケイ", kunyomi: "はか.る", examples: [{ word: "時計", reading: "tokei", mean: "နာရီ" }] },
  { id: 89, kanji: "集", meaning: "စုစည်းသည် (Gather)", onyomi: "シュウ", kunyomi: "あつ.まる", examples: [{ word: "集合", reading: "shuugou", mean: "စုဝေးခြင်း" }] },
  { id: 90, kanji: "便", meaning: "အဆင်ပြေရခြင်း (Convenience/Flight)", onyomi: "ベン/ビン", kunyomi: "たより", examples: [{ word: "郵便局", reading: "yuubinkyoku", mean: "စာတိုက်" }] },
  { id: 91, kanji: "利", meaning: "အကျိုးအမြတ် (Profit/Advantage)", onyomi: "リ", kunyomi: "き.く", examples: [{ word: "利用", reading: "riyou", mean: "အသုံးပြုခြင်း" }] },
  { id: 92, kanji: "特", meaning: "ထူးခြားသော (Special)", onyomi: "トク", kunyomi: "-", examples: [{ word: "特別に", reading: "tokubetsu ni", mean: "အထူးသဖြင့်" }] },
  { id: 93, kanji: "別", meaning: "သီးခြား (Separate/Different)", onyomi: "ベツ", kunyomi: "わか.れる", examples: [{ word: "別に", reading: "betsu ni", mean: "ဘာမှမဟုတ်ပါ/သီးခြား" }] },
  { id: 94, kanji: "有", meaning: "ရှိသည် (Exist/Have)", onyomi: "ユウ/ウ", kunyomi: "あ.る", examples: [{ word: "有名", reading: "yuumei", mean: "နာမည်ကြီးသော" }] },
  { id: 95, kanji: "無", meaning: "မရှိ (Nothing/Nil)", onyomi: "ム/ブ", kunyomi: "な.い", examples: [{ word: "無理", reading: "muri", mean: "မဖြစ်နိုင်သော" }] },
  { id: 96, kanji: "働", meaning: "အလုပ်လုပ်သည် (Work)", onyomi: "ドウ", kunyomi: "はたら.く", examples: [{ word: "労働", reading: "roudou", mean: "အလုပ်သမား" }] },
  { id: 97, kanji: "運", meaning: "ကံ/သယ်ဆောင်သည် (Fortune/Carry)", onyomi: "ウン", kunyomi: "はこ.ぶ", examples: [{ word: "運動", reading: "undou", mean: "လေ့ကျင့်ခန်း" }] },
  { id: 98, kanji: "動", meaning: "လှုပ်ရှားသည် (Move)", onyomi: "ドウ", kunyomi: "うご.く", examples: [{ word: "自動車", reading: "jidousha", mean: "ကား" }] },
  { id: 99, kanji: "止", meaning: "ရပ်သည် (Stop)", onyomi: "シ", kunyomi: "と.まる", examples: [{ word: "中止", reading: "chuushi", mean: "ဖျက်သိမ်းခြင်း" }] },
  { id: 100, kanji: "歩", meaning: "လမ်းလျှောက်သည် (Walk)", onyomi: "ホ", kunyomi: "ある.く", examples: [{ word: "散歩", reading: "sanpo", mean: "လမ်းလျှောက်ထွက်ခြင်း" }] },
  { id: 101, kanji: "建", meaning: "တည်ဆောက်သည် (Build)", onyomi: "ケン", kunyomi: "た.てる", examples: [{ word: "建物", reading: "tatemono", mean: "အဆောက်အဦး" }, { word: "建設", reading: "kensetsu", mean: "တည်ဆောက်ရေး" }] },
  { id: 102, kanji: "物", meaning: "အရာဝတ္ထု (Thing)", onyomi: "ブツ/モツ", kunyomi: "もの", examples: [{ word: "荷物", reading: "nimotsu", mean: "အထုတ်အပိုး" }, { word: "動物", reading: "doubutsu", mean: "တိရစ္ဆာန်" }] },
  { id: 103, kanji: "所", meaning: "နေရာ (Place)", onyomi: "ショ", kunyomi: "ところ", examples: [{ word: "住所", reading: "juusho", mean: "လိပ်စာ" }, { word: "台所", reading: "daidokoro", mean: "မီးဖိုချောင်" }] },
  { id: 104, kanji: "場", meaning: "နေရာ/ကွင်း (Place/Scene)", onyomi: "ジョウ", kunyomi: "ば", examples: [{ word: "場所", reading: "basho", mean: "နေရာ" }, { word: "工場", reading: "koujou", mean: "စက်ရုံ" }] },
  { id: 105, kanji: "待", meaning: "စောင့်သည် (Wait)", onyomi: "タイ", kunyomi: "ま.つ", examples: [{ word: "招待", reading: "shoutai", mean: "ဖိတ်ကြားခြင်း" }, { word: "期待", reading: "kitai", mean: "မျှော်လင့်ခြင်း" }] },
  { id: 106, kanji: "持", meaning: "ကိုင်ဆောင်သည် (Hold/Have)", onyomi: "ジ", kunyomi: "も.つ", examples: [{ word: "気持ち", reading: "kimochi", mean: "ခံစားချက်" }, { word: "持参", reading: "jisan", mean: "ယူဆောင်လာခြင်း" }] },
  { id: 107, kanji: "帰", meaning: "ပြန်သည် (Return)", onyomi: "キ", kunyomi: "かえ.る", examples: [{ word: "帰国", reading: "kikoku", mean: "နိုင်ငံသို့ပြန်ခြင်း" }, { word: "帰り道", reading: "kaerimichi", mean: "အပြန်လမ်း" }] },
  { id: 108, kanji: "使", meaning: "အသုံးပြုသည် (Use)", onyomi: "シ", kunyomi: "つか.う", examples: [{ word: "大使館", reading: "taishikan", mean: "သံရုံး" }, { word: "使用", reading: "shiyou", mean: "အသုံးပြုမှု" }] },
  { id: 109, kanji: "作", meaning: "ပြုလုပ်သည် (Make)", onyomi: "サク/サ", kunyomi: "つく.る", examples: [{ word: "作文", reading: "sakubun", mean: "စီကာပတ်ကုံး" }, { word: "作家", reading: "sakka", mean: "စာရေးဆရာ" }] },
  { id: 110, kanji: "買", meaning: "ဝယ်သည် (Buy)", onyomi: "バイ", kunyomi: "か.う", examples: [{ word: "買い物", reading: "kaimono", mean: "ဈေးဝယ်ခြင်း" }, { word: "売買", reading: "baibai", mean: "အရောင်းအဝယ်" }] },
  { id: 111, kanji: "売", meaning: "ရောင်းသည် (Sell)", onyomi: "バイ", kunyomi: "う.る", examples: [{ word: "売店", reading: "baiten", mean: "အရောင်းဆိုင်" }, { word: "売り場", reading: "uriba", mean: "အရောင်းကောင်တာ" }] },
  { id: 112, kanji: "洗", meaning: "ဆေးကြောသည် (Wash)", onyomi: "セン", kunyomi: "あら.う", examples: [{ word: "洗濯", reading: "sentaku", mean: "အဝတ်လျှော်ခြင်း" }, { word: "洗面所", reading: "senmenjo", mean: "မျက်နှာသစ်ခန်း" }] },
  { id: 113, kanji: "引", meaning: "ဆွဲသည် (Pull)", onyomi: "イン", kunyomi: "ひ.く", examples: [{ word: "引き出し", reading: "hikidashi", mean: "အံဆွဲ" }, { word: "引退", reading: "intai", mean: "အနားယူခြင်း" }] },
  { id: 114, kanji: "押", meaning: "တွန်းသည် (Push)", onyomi: "オウ", kunyomi: "お.す", examples: [{ word: "押し入れ", reading: "oshiire", mean: "နံရံကပ်ဗီရို" }] },
  { id: 115, kanji: "降", meaning: "ဆင်းသည်/ရွာသည် (Get off/Fall)", onyomi: "コウ", kunyomi: "お.りる/ふ.る", examples: [{ word: "降車", reading: "kousha", mean: "ကားပေါ်မှဆင်းခြင်း" }, { word: "降雪", reading: "kousetsu", mean: "နှင်းကျခြင်း" }] },
  { id: 116, kanji: "走", meaning: "ပြေးသည် (Run)", onyomi: "ソウ", kunyomi: "はし.る", examples: [{ word: "走者", reading: "sousha", mean: "အပြေးသမား" }] },
  { id: 117, kanji: "泳", meaning: "ရေကူးသည် (Swim)", onyomi: "エイ", kunyomi: "よよ.ぐ", examples: [{ word: "水泳", reading: "suieiu", mean: "ရေကူးခြင်း" }] },
  { id: 118, kanji: "試", meaning: "စမ်းသပ်သည် (Test/Try)", onyomi: "シ", kunyomi: "こころ.みる", examples: [{ word: "試験", reading: "shiken", mean: "စာမေးပွဲ" }, { word: "試合", reading: "shiai", mean: "ပွဲစဉ်" }] },
  { id: 119, kanji: "験", meaning: "စစ်ဆေးသည် (Examination)", onyomi: "ケン", kunyomi: "-", examples: [{ word: "経験", reading: "keiken", mean: "အတွေ့အကြုံ" }, { word: "受験", reading: "juken", mean: "စာမေးပွဲဖြေဆိုခြင်း" }] },
  { id: 120, kanji: "題", meaning: "ခေါင်းစဉ် (Topic/Title)", onyomi: "ダイ", kunyomi: "-", examples: [{ word: "問題", reading: "mondai", mean: "ပြဿနာ/မေးခွန်း" }, { word: "宿題", reading: "shukudai", mean: "အိမ်စာ" }] },
  { id: 121, kanji: "問", meaning: "မေးခွန်း (Question)", onyomi: "モン", kunyomi: "と.う", examples: [{ word: "質問", reading: "shitsumon", mean: "မေးခွန်း" }, { word: "問い合わせ", reading: "toiawase", mean: "စုံစမ်းမေးမြန်းခြင်း" }] },
  { id: 122, kanji: "質", meaning: "အရည်အသွေး/မေးခွန်း (Quality/Inquiry)", onyomi: "シツ", kunyomi: "-", examples: [{ word: "品質", reading: "hinshitsu", mean: "အရည်အသွေး" }, { word: "性格", reading: "seikaku", mean: "စိတ်နေစိတ်ထား" }] },
  { id: 123, kanji: "文", meaning: "စာသား (Sentence/Text)", onyomi: "ブン/モン", kunyomi: "ふみ", examples: [{ word: "文学", reading: "bungaku", mean: "စာပေ" }, { word: "文法", reading: "bunpou", mean: "သဒ္ဒါ" }] },
  { id: 124, kanji: "字", meaning: "အက္ခရာ (Character/Letter)", onyomi: "ジ", kunyomi: "あざ", examples: [{ word: "漢字", reading: "kanji", mean: "ခန်ဂျီ" }, { word: "文字", reading: "moji", mean: "စာလုံး" }] },
  { id: 125, kanji: "研", meaning: "သုတေသနပြုသည် (Research/Polish)", onyomi: "ケン", kunyomi: "と.ぐ", examples: [{ word: "研究", reading: "kenkyuu", mean: "သုတေသန" }, { word: "研修", reading: "kenshuu", mean: "သင်တန်း" }] },
  { id: 126, kanji: "究", meaning: "စုံစမ်းစစ်ဆေးသည် (Research/Study)", onyomi: "キュウ", kunyomi: "きわ.める", examples: [{ word: "探究", reading: "tankyuu", mean: "ရှာဖွေစူးစမ်းခြင်း" }] },
  { id: 127, kanji: "員", meaning: "ဝန်ထမ်း/အဖွဲ့ဝင် (Member/Employee)", onyomi: "イン", kunyomi: "-", examples: [{ word: "社員", reading: "shain", mean: "ဝန်ထမ်း" }, { word: "銀行員", reading: "ginkouin", mean: "ဘဏ်ဝန်ထမ်း" }] },
  { id: 128, kanji: "者", meaning: "လူ (Person)", onyomi: "シャ", kunyomi: "もの", examples: [{ word: "医者", reading: "isha", mean: "ဆရာဝန်" }, { word: "学者", reading: "gakusha", mean: "ပညာရှင်" }] },
  { id: 129, kanji: "業", meaning: "လုပ်ငန်း (Business/Industry)", onyomi: "ギョウ", kunyomi: "わざ", examples: [{ word: "授業", reading: "jugyou", mean: "သင်ခန်းစာ" }, { word: "工業", reading: "kougyou", mean: "စက်မှုလက်မှု" }] },
  { id: 130, kanji: "意", meaning: "အဓိပ္ပာယ်/စိတ်ကူး (Meaning/Intention)", onyomi: "イ", kunyomi: "-", examples: [{ word: "意見", reading: "iken", mean: "အမြင်/သဘောထား" }, { word: "意味", reading: "imi", mean: "အဓိပ္ပာယ်" }] },
  { id: 131, kanji: "味", meaning: "အရသာ (Taste)", onyomi: "ミ", kunyomi: "あじ", examples: [{ word: "趣味", reading: "shumi", mean: "ဝါသနာ" }, { word: "興味", reading: "kyoumi", mean: "စိတ်ဝင်စားမှု" }] },
  { id: 132, kanji: "事", meaning: "အကြောင်းအရာ (Matter/Thing)", onyomi: "ジ", kunyomi: "こと", examples: [{ word: "仕事", reading: "shigoto", mean: "အလုပ်" }, { word: "大事", reading: "daiji", mean: "အရေးကြီးသော" }] },
  { id: 133, kanji: "料", meaning: "ကုန်ကြမ်း/အခကြေးငွေ (Material/Fee)", onyomi: "リョウ", kunyomi: "-", examples: [{ word: "料金", reading: "ryoukin", mean: "အခကြေးငွေ" }, { word: "料理", reading: "ryouri", mean: "ဟင်းလျာ" }] },
  { id: 134, kanji: "理", meaning: "အကြောင်းပြချက် (Reason/Logic)", onyomi: "リ", kunyomi: "ことわり", examples: [{ word: "理由", reading: "riyuu", mean: "အကြောင်းပြချက်" }, { word: "理解", reading: "rikai", mean: "နားလည်မှု" }] },
  { id: 135, kanji: "野", meaning: "ကွင်းပြင် (Field)", onyomi: "ヤ", kunyomi: "の", examples: [{ word: "分野", reading: "bunya", mean: "နယ်ပယ်" }, { word: "野菜", reading: "yasai", mean: "ဟင်းသီးဟင်းရွက်" }] },
  { id: 136, kanji: "菜", meaning: "ဟင်းသီးဟင်းရွက် (Vegetable)", onyomi: "サイ", kunyomi: "な", examples: [{ word: "白菜", reading: "hakusai", mean: "မုန်လာထုပ်" }] },
  { id: 137, kanji: "果", meaning: "အသီး (Fruit/Result)", onyomi: "カ", kunyomi: "は.たす", examples: [{ word: "果物", reading: "kudamono", mean: "သစ်သီး" }, { word: "結果", reading: "kekka", mean: "ရလဒ်" }] },
  { id: 138, kanji: "魚", meaning: "ငါး (Fish)", onyomi: "ギョ", kunyomi: "さかな", examples: [{ word: "金魚", reading: "kingyo", mean: "ရွှေငါး" }] },
  { id: 139, kanji: "肉", meaning: "အသား (Meat)", onyomi: "ニク", kunyomi: "-", examples: [{ word: "牛肉", reading: "gyuuniku", mean: "အမဲသား" }, { word: "筋肉", reading: "kinniku", mean: "ကြွက်သား" }] },
  { id: 140, kanji: "飯", meaning: "ထမင်း (Meal/Rice)", onyomi: "ハン", kunyomi: "めし", examples: [{ word: "朝御飯", reading: "asagohan", mean: "မနက်စာ" }, { word: "夕飯", reading: "yuuhan", mean: "ညစာ" }] },
  { id: 141, kanji: "晩", meaning: "ညဦးပိုင်း (Evening)", onyomi: "バン", kunyomi: "-", examples: [{ word: "今晩", reading: "konban", mean: "ယနေ့ည" }, { word: "晩御飯", reading: "bangohan", mean: "ညစာ" }] },
  { id: 142, kanji: "門", meaning: "တံခါးမကြီး (Gate)", onyomi: "モン", kunyomi: "かど", examples: [{ word: "正門", reading: "seimon", mean: "အဓိကတံခါးမကြီး" }, { word: "専門", reading: "senmon", mean: "အထူးပြုဘာသာရပ်" }] },
  { id: 143, kanji: "開", meaning: "ဖွင့်သည် (Open)", onyomi: "カイ", kunyomi: "あ.ける", examples: [{ word: "開始", reading: "kaishi", mean: "စတင်ခြင်း" }, { word: "開会", reading: "kaikai", mean: "အခမ်းအနားဖွင့်လှစ်ခြင်း" }] },
  { id: 144, kanji: "閉", meaning: "ပိတ်သည် (Close)", onyomi: "ヘイ", kunyomi: "し.める", examples: [{ word: "閉会", reading: "heikai", mean: "အခမ်းအနားပိတ်သိမ်းခြင်း" }, { word: "閉鎖", reading: "heisa", mean: "ပိတ်ပစ်ခြင်း" }] },
  { id: 145, kanji: "春", meaning: "နွေဦးရာသီ (Spring)", onyomi: "シュン", kunyomi: "はる", examples: [{ word: "春分", reading: "shunbun", mean: "နွေဦးနေ့ညညီချိန်" }] },
  { id: 146, kanji: "夏", meaning: "နွေရာသီ (Summer)", onyomi: "カ", kunyomi: "なつ", examples: [{ word: "夏休み", reading: "natsuyasumi", mean: "နွေရာသီကျောင်းပိတ်ရက်" }] },
  { id: 147, kanji: "秋", meaning: "ဆောင်းဦးရာသီ (Autumn)", onyomi: "シュウ", kunyomi: "あき", examples: [{ word: "秋分", reading: "shuubun", mean: "ဆောင်းဦးနေ့ညညီချိန်" }] },
  { id: 148, kanji: "冬", meaning: "ဆောင်းရာသီ (Winter)", onyomi: "トウ", kunyomi: "ふゆ", examples: [{ word: "冬休み", reading: "fuyuyasumi", mean: "ဆောင်းရာသီကျောင်းပိတ်ရက်" }] },
  { id: 149, kanji: "風", meaning: "လေ (Wind)", onyomi: "フウ", kunyomi: "かぜ", examples: [{ word: "台風", reading: "taifuu", mean: "တိုင်ဖွန်းမုန်တိုင်း" }, { word: "和風", reading: "wafuu", mean: "ဂျပန်စတိုင်" }] },
  { id: 150, kanji: "雲", meaning: "တိမ် (Cloud)", onyomi: "ウン", kunyomi: "くも", examples: [{ word: "雨雲", reading: "amagumo", mean: "မိုးတိမ်" }] }
];

// Helper to chunk the data into separate decks
const chunkArray = (arr: any[], size: number) =>
  Array.from({ length: Math.ceil(arr.length / size) }, (v, i) =>
    arr.slice(i * size, i * size + size)
  );

const chunks = chunkArray(N4_KANJI_DATA, 50);

export const DEFAULT_DECKS: Deck[] = chunks.map((cards, index) => ({
  id: `n4-v2-p${index + 1}`,
  title: `N4 Kanji Part ${index + 1}`,
  cards: cards
}));
